import net from "net"
import { GetShoppingMallListReq, GetShoppingMallListRsp, GetShoppingMallListRsp_CmdId, GetShoppingMallListRsp_Retcode, Goods_RefreshTimeType, Shop } from "../../BengHuai"
import Packet from "../Packet"

export default (socket: net.Socket, packet: GetShoppingMallListReq) => {
    Packet.getInstance().serializeAndSend(socket, GetShoppingMallListRsp_CmdId.CMD_ID, {
        retcode: GetShoppingMallListRsp_Retcode.SUCC,
        shopList: [
            {
                "shopId": 27,
                "isOpen": true,
                "textMapName": "ShopName27",
                "shopIconPath": "SpriteOutput\\ShopTabIcons\\IconShopNewbie",
                "goodsList": [
                    {
                        "goodsId": 16000226,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 996,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 50,
                        "minLevel": 50,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000227,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 994,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 60,
                        "minLevel": 60,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000228,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 992,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 70,
                        "minLevel": 70,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000229,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 989,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 81,
                        "minLevel": 81,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000234,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 95,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": true,
                        "prepareLevel": 61,
                        "minLevel": 61,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000235,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 95,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": true,
                        "prepareLevel": 50,
                        "minLevel": 50,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000236,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 95,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": true,
                        "prepareLevel": 70,
                        "minLevel": 70,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000237,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1554955200,
                        "endTime": 1767153600,
                        "prepareTime": 1554955200,
                        "sortId": 94,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 70,
                        "minLevel": 70,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 671611,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1662091200,
                        "endTime": 2085105600,
                        "prepareTime": 1662091200,
                        "sortId": 28,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 671621,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1662091200,
                        "endTime": 2085105600,
                        "prepareTime": 1662091200,
                        "sortId": 30,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 671631,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1662091200,
                        "endTime": 2085105600,
                        "prepareTime": 1662091200,
                        "sortId": 62,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 672761,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1668139200,
                        "endTime": 2051207999,
                        "prepareTime": 1668139200,
                        "sortId": 55,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 719824,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1677211200,
                        "endTime": 1678420800,
                        "prepareTime": 1677211200,
                        "sortId": 399,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            1,
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000550,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1569441600,
                        "endTime": 1767153600,
                        "prepareTime": 1569441600,
                        "sortId": 991,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 70,
                        "minLevel": 70,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000551,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1569441600,
                        "endTime": 1767153600,
                        "prepareTime": 1569441600,
                        "sortId": 988,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 82,
                        "minLevel": 82,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000552,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1569441600,
                        "endTime": 1767153600,
                        "prepareTime": 1569441600,
                        "sortId": 987,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 83,
                        "minLevel": 83,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000553,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1569441600,
                        "endTime": 1767153600,
                        "prepareTime": 1569441600,
                        "sortId": 986,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 84,
                        "minLevel": 84,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000554,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1569441600,
                        "endTime": 1767153600,
                        "prepareTime": 1569441600,
                        "sortId": 985,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 85,
                        "minLevel": 85,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000555,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1569441600,
                        "endTime": 1767153600,
                        "prepareTime": 1569441600,
                        "sortId": 210,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": true,
                        "prepareLevel": 81,
                        "minLevel": 81,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000616,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 56,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000617,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 55,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000618,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 45,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000619,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 47,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000620,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 54,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000621,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 42,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000622,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 43,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000623,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 53,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000624,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 52,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000625,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 49,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000626,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 44,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000627,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 48,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000628,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 46,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000629,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 51,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16000630,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1572552001,
                        "endTime": 1767153600,
                        "prepareTime": 1572552001,
                        "sortId": 50,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300218,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1573675200,
                        "endTime": 1767153600,
                        "prepareTime": 1573675200,
                        "sortId": 99,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            200,
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 9,
                        "minLevel": 9,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300436,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1577304000,
                        "endTime": 1767153600,
                        "prepareTime": 1577304000,
                        "sortId": 100,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": true,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300437,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1577304000,
                        "endTime": 1767153600,
                        "prepareTime": 1577304000,
                        "sortId": 99,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": true,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300438,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1577304000,
                        "endTime": 1767153600,
                        "prepareTime": 1577304000,
                        "sortId": 98,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": true,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300559,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 3,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 35,
                        "minLevel": 35,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300560,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 5,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300561,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 4,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300562,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 99,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300563,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 99,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300564,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 7,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300565,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 6,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 14,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300557,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 60,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": true,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300558,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1581537600,
                        "endTime": 1767153600,
                        "prepareTime": 1581537600,
                        "sortId": 59,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": true,
                        "prepareLevel": 15,
                        "minLevel": 15,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300639,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1586138400,
                        "endTime": 1767153600,
                        "prepareTime": 1586138400,
                        "sortId": 49,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            300,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 40,
                        "minLevel": 40,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16300640,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "DAY_TYPE",
                        "beginTime": 1586138400,
                        "endTime": 1767153600,
                        "prepareTime": 1586138400,
                        "sortId": 49,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 19421,
                        "mallAnchorList": [
                            300
                        ],
                        "isIgnore": false,
                        "prepareLevel": 40,
                        "minLevel": 40,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 700596,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1600135200,
                        "endTime": 1767124800,
                        "prepareTime": 1600135200,
                        "sortId": 995,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 55,
                        "minLevel": 55,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 700597,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1600135200,
                        "endTime": 1767124800,
                        "prepareTime": 1600135200,
                        "sortId": 993,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 65,
                        "minLevel": 65,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 700598,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1600135200,
                        "endTime": 1767124800,
                        "prepareTime": 1600135200,
                        "sortId": 990,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 75,
                        "minLevel": 75,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 710159,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1553220000,
                        "endTime": 1767153600,
                        "prepareTime": 1553220000,
                        "sortId": 997,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 40,
                        "minLevel": 40,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16301552,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1607313600,
                        "endTime": 1767153600,
                        "prepareTime": 1607313600,
                        "sortId": 73,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            6
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 716321,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1619035200,
                        "endTime": 1767153600,
                        "prepareTime": 1619035200,
                        "sortId": 999,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 80,
                        "minLevel": 80,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 716322,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1619035200,
                        "endTime": 1767153600,
                        "prepareTime": 1619035200,
                        "sortId": 999,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 86,
                        "minLevel": 86,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 716323,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1619035200,
                        "endTime": 1767153600,
                        "prepareTime": 1619035200,
                        "sortId": 999,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 87,
                        "minLevel": 87,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 716324,
                        "buyTimes": 1,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1619035200,
                        "endTime": 1767153600,
                        "prepareTime": 1619035200,
                        "sortId": 999,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            8
                        ],
                        "isIgnore": true,
                        "prepareLevel": 88,
                        "minLevel": 88,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303614,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1638302400,
                        "endTime": 1767153600,
                        "prepareTime": 1638259200,
                        "sortId": 93,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303615,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1638302400,
                        "endTime": 1767153600,
                        "prepareTime": 1638259200,
                        "sortId": 94,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303616,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1638302400,
                        "endTime": 1767153600,
                        "prepareTime": 1638259200,
                        "sortId": 99,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            1,
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303617,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "MONTH_TYPE",
                        "beginTime": 1638302400,
                        "endTime": 1767153600,
                        "prepareTime": 1638259200,
                        "sortId": 98,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 638,
                        "mallAnchorList": [
                            1,
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303618,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "MONTH_TYPE",
                        "beginTime": 1638302400,
                        "endTime": 1767153600,
                        "prepareTime": 1638259200,
                        "sortId": 95,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 638,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303621,
                        "buyTimes": 1,
                        "canBeRefresh": true,
                        "refreshTimeType": "WEEK_TYPE",
                        "beginTime": 1638302400,
                        "endTime": 1767153600,
                        "prepareTime": 1638259200,
                        "sortId": 999,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 2774,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303802,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "MONTH_TYPE",
                        "beginTime": 1643659200,
                        "endTime": 1767153599,
                        "prepareTime": 1643616000,
                        "sortId": 96,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 638,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303803,
                        "buyTimes": 0,
                        "canBeRefresh": true,
                        "refreshTimeType": "MONTH_TYPE",
                        "beginTime": 1643659200,
                        "endTime": 1767153599,
                        "prepareTime": 1643616000,
                        "sortId": 97,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 638,
                        "mallAnchorList": [
                            9
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303936,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 30,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303937,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 28,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303938,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 26,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303939,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 24,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303940,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 22,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303941,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 20,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303942,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 18,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303943,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 16,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303944,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 14,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303945,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 12,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303946,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 10,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303947,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 8,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303948,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 6,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303949,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 4,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16303950,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1645156800,
                        "endTime": 1767153600,
                        "prepareTime": 1645156800,
                        "sortId": 2,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16304488,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1651204800,
                        "endTime": 2051236800,
                        "prepareTime": 1651204800,
                        "sortId": 35,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16304489,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1651204800,
                        "endTime": 2051236800,
                        "prepareTime": 1651204800,
                        "sortId": 34,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16304490,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1651204800,
                        "endTime": 2051236800,
                        "prepareTime": 1651204800,
                        "sortId": 33,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16304598,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1654833600,
                        "endTime": 1767153600,
                        "prepareTime": 1654833600,
                        "sortId": 38,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16304964,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1658462400,
                        "endTime": 2051236800,
                        "prepareTime": 1658462400,
                        "sortId": 31,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305146,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1670443200,
                        "endTime": 2051207999,
                        "prepareTime": 1670443200,
                        "sortId": 54,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305147,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1670443200,
                        "endTime": 2051207999,
                        "prepareTime": 1670443200,
                        "sortId": 34,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305148,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1670443200,
                        "endTime": 2051207999,
                        "prepareTime": 1670443200,
                        "sortId": 33,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305373,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1672977600,
                        "endTime": 2051207999,
                        "prepareTime": 1672977600,
                        "sortId": 54,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305493,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1674100800,
                        "endTime": 2051207999,
                        "prepareTime": 1674100800,
                        "sortId": 92,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305495,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1674100800,
                        "endTime": 2051207999,
                        "prepareTime": 1674100800,
                        "sortId": 88,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            5
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305605,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 350,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305609,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 340,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305610,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 333,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305611,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 320,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305612,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1677211200,
                        "endTime": 1678593600,
                        "prepareTime": 1677196800,
                        "sortId": 341,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305613,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1677211200,
                        "endTime": 1678593600,
                        "prepareTime": 1677196800,
                        "sortId": 334,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305614,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 346,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305617,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 337,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305618,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 330,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305619,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1677211200,
                        "endTime": 1678593600,
                        "prepareTime": 1677196800,
                        "sortId": 338,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305620,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1677211200,
                        "endTime": 1678593600,
                        "prepareTime": 1677196800,
                        "sortId": 331,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305621,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1677816000,
                        "endTime": 1679025600,
                        "prepareTime": 1677816000,
                        "sortId": 332,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305622,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 335,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 61,
                        "minLevel": 61,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305624,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1677816000,
                        "endTime": 1678593600,
                        "prepareTime": 1677801600,
                        "sortId": 336,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 61,
                        "minLevel": 61,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    },
                    {
                        "goodsId": 16305625,
                        "buyTimes": 0,
                        "canBeRefresh": false,
                        "refreshTimeType": Goods_RefreshTimeType.SHOP_TYPE,
                        "beginTime": 1676491200,
                        "endTime": 1679025600,
                        "prepareTime": 1676491200,
                        "sortId": 315,
                        "showSettingStr": "NORMAL",
                        "showNewTag": 0,
                        "mallAnchorList": [
                            200,
                            1
                        ],
                        "isIgnore": false,
                        "prepareLevel": 20,
                        "minLevel": 20,
                        "maxLevel": 99,
                        "isPopup": false,
                        "isHidePrice": false
                    }
                ],
                "nextAutoRefreshTime": 1678046400,
                "manualRefreshTimes": 0,
                "refreshItem": 0,
                "nextRefreshCost": 4294967295,
                "maxManualRefreshTimes": 0,
                "shopType": 201,
                "scheduleChangeTime": 1905710400,
                "shopName": "ShopName27",
                "unlockLevel": 10,
                "beginTime": 1572638400,
                "endTime": 1905710399,
                "isHot": false,
                "multiCurrency": 0,
                "isDoubleConfirm": false,
                "isShow": true,
                "sortPriority": 27,
                "toolbarCurrencyList": [
                    1,
                    2,
                    3
                ],
                "freeManualRefreshTimes": 0
            }
        ] as Partial<Shop>[]
    } as GetShoppingMallListRsp)
}